// ABOUTME: Entry for /resources/articles/part-1-operational-excellence/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the allowlist; the Markdown is in content/collateral.

import markdown from "../../../../content/collateral/articles/part-1-operational-excellence.md?raw";
import { mountPage } from "../../../../src/pages/Page";
import { DocumentPage } from "../../../../src/pages/Document";

mountPage(<DocumentPage slug="articles/part-1-operational-excellence" markdown={markdown} />);
