// ABOUTME: Entry for /resources/approval-process-criteria/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the allowlist; the Markdown is in content/collateral.

import markdown from "../../../content/collateral/approval-process-criteria.md?raw";
import { mountPage } from "../../../src/pages/Page";
import { DocumentPage } from "../../../src/pages/Document";

mountPage(<DocumentPage slug="approval-process-criteria" markdown={markdown} />);
