// ABOUTME: Entry for /resources/source-ledger/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the manifest; the Markdown is in content/collateral.

import markdown from "../../../content/collateral/source-ledger.md?raw";
import { mountPage } from "../../pages/Page";
import { DocumentPage } from "../../pages/Document";

mountPage(<DocumentPage slug="source-ledger" markdown={markdown} />);
