// ABOUTME: Entry for /resources/sources/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the allowlist; the Markdown is in content/collateral.

import markdown from "../../../content/collateral/sources.md?raw";
import { mountPage } from "../../../src/pages/mount";
import { DocumentPage } from "../../../src/pages/Document";

mountPage(<DocumentPage slug="sources" markdown={markdown} />);
