// ABOUTME: Entry for /resources/wrapping-mcp-servers/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the allowlist; the Markdown is in content/collateral.

import markdown from "../../../content/collateral/wrapping-mcp-servers.md?raw";
import { mountPage } from "../../../src/pages/Page";
import { DocumentPage } from "../../../src/pages/Document";

mountPage(<DocumentPage slug="wrapping-mcp-servers" markdown={markdown} />);
