// ABOUTME: Copies the allowlisted public documents from the collateral repo into content/collateral, with provenance.
// ABOUTME: Run with `node scripts/sync-collateral.ts [path-to-mcp-for-a-city]`; nothing outside the allowlist ever crosses.

import { execSync } from "node:child_process";
import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

/** Every document the site renders from peopleforrester/mcp-for-a-city. A file not listed here is not published. */
export interface Collateral {
  src: string;
  slug: string;
  title: string;
  series?: string;
  status?: string;
}

export const COLLATERAL: Collateral[] = [
  { src: "research/approval-process-criteria.md", slug: "approval-process-criteria", title: "What an enterprise MCP approval process evaluates" },
  { src: "research/wrapping-mcp-servers.md", slug: "wrapping-mcp-servers", title: "Wrapping an MCP server inside an MCP server" },
  { src: "research/source-ledger.md", slug: "source-ledger", title: "The claim-by-claim source ledger" },
  { src: "sources/sources.md", slug: "sources", title: "The sources slide" },
  { src: "gates/approval-gates.md", slug: "approval-gates", title: "The six approval gates as a checklist" },
  { src: "articles/part-1-operational-excellence.md", slug: "articles/part-1-operational-excellence", title: "The Protocol Moved Under You and Nobody Migrates You", series: "Operating MCP at Scale, part 1: operational excellence", status: "draft, under review" },
  { src: "articles/part-2-security.md", slug: "articles/part-2-security", title: "Nobody Vets MCP Servers, and Everyone Is Right About Why", series: "Operating MCP at Scale, part 2: security", status: "draft, under review" },
  { src: "articles/part-3-reliability.md", slug: "articles/part-3-reliability", title: "Your Health Check Is Speaking a Different Protocol Version", series: "Operating MCP at Scale, part 3: reliability", status: "draft, under review" },
];

/** The HTML entry and the mount module for /resources/<slug>/, so a new document is one line in the allowlist. */
function writeEntry(c: Collateral) {
  const route = `resources/${c.slug}`;
  const desc = (c.series ? `${c.series}. ` : "") + "From the collateral of Governing MCP for a Workforce the Size of a City, MCP Dev Summit Toronto 2026.";
  mkdirSync(route, { recursive: true });
  writeFileSync(
    `${route}/index.html`,
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${c.title}</title>
    <meta name="description" content="${desc}" />
    <meta property="og:title" content="${c.title}" />
    <meta property="og:image" content="https://mcp.michaelrishiforrester.com/art/og.jpg" />
    <meta property="og:url" content="https://mcp.michaelrishiforrester.com/${route}/" />
    <link rel="canonical" href="https://mcp.michaelrishiforrester.com/${route}/" />
    <meta name="theme-color" content="#051932" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/entries/${route}.tsx"></script>
  </body>
</html>
`,
  );
  const entry = `src/entries/${route}.tsx`;
  mkdirSync(dirname(entry), { recursive: true });
  const up = relative(dirname(entry), ".").replace(/\\/g, "/");
  writeFileSync(
    entry,
    `// ABOUTME: Entry for /${route}/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the allowlist; the Markdown is in content/collateral.

import markdown from "${up}/content/collateral/${c.slug}.md?raw";
import { mountPage } from "${up}/src/pages/Page";
import { DocumentPage } from "${up}/src/pages/Document";

mountPage(<DocumentPage slug="${c.slug}" markdown={markdown} />);
`,
  );
}

const repo = resolve(process.argv[2] ?? "../../talks/mcp-for-a-city");
const sha = execSync("git rev-parse --short HEAD", { cwd: repo }).toString().trim();
mkdirSync("content/collateral", { recursive: true });
for (const c of COLLATERAL) {
  const dest = `content/collateral/${c.slug}.md`;
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(resolve(repo, c.src), dest);
  writeEntry(c);
}
writeFileSync("content/collateral/manifest.json", JSON.stringify({ repo: "peopleforrester/mcp-for-a-city", commit: sha, synced: new Date().toISOString().slice(0, 10), documents: COLLATERAL }, null, 1) + "\n");
console.log(`synced ${COLLATERAL.length} documents at ${sha}`);
