// ABOUTME: Entry for /resources/research/mcp-token-economics-and-tool-consolidation/. Mounts the rendered document into the shared shell.
// ABOUTME: Generated by scripts/sync-collateral.ts from the allowlist; the Markdown is in content/collateral.

import markdown from "../../../../content/collateral/research/mcp-token-economics-and-tool-consolidation.md?raw";
import { mountPage } from "../../../../src/pages/mount";
import { DocumentPage } from "../../../../src/pages/Document";

mountPage(<DocumentPage slug="research/mcp-token-economics-and-tool-consolidation" markdown={markdown} />);
